ascii_composer:
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: noop
    Shift_L: commit_text
    Shift_R: inline_ascii
config_version: .custom.384736881
customization: 384736881
menu:
  page_size: 5
patch:
  schema_list:
    - {schema: xhup}
    - {schema: wubi_pinyin}
schema_list:
  - schema: wubi86
  - schema: xhup
  - schema: pinyin_simp
style:
  color_scheme: luna
  horizontal: true
switcher:
  abbreviate_options: true
  caption: "〔切换〕"
  fold_options: true
  hotkeys:
    - "Control+grave"
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
